// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoDDZ1S4sLrjnlwCHbqyrApdCM4Z8ulBs',
    appId: '1:922484244108:web:c9a9603ec0e33192d605a9',
    messagingSenderId: '922484244108',
    projectId: 'bbm-pln',
    authDomain: 'bbm-pln.firebaseapp.com',
    storageBucket: 'bbm-pln.firebasestorage.app',
    measurementId: 'G-XPVFWYSCD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3GaP_fJoTueooZZUpMFlfZ2kJr0BR8dA',
    appId: '1:922484244108:android:f564146a05ec1d42d605a9',
    messagingSenderId: '922484244108',
    projectId: 'bbm-pln',
    storageBucket: 'bbm-pln.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCemWP5M9UHxXXhab6FHpW8UbV9pQg3ocE',
    appId: '1:922484244108:ios:5b886f3470a760f0d605a9',
    messagingSenderId: '922484244108',
    projectId: 'bbm-pln',
    storageBucket: 'bbm-pln.firebasestorage.app',
    iosBundleId: 'com.example.bbmPln',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCemWP5M9UHxXXhab6FHpW8UbV9pQg3ocE',
    appId: '1:922484244108:ios:5b886f3470a760f0d605a9',
    messagingSenderId: '922484244108',
    projectId: 'bbm-pln',
    storageBucket: 'bbm-pln.firebasestorage.app',
    iosBundleId: 'com.example.bbmPln',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoDDZ1S4sLrjnlwCHbqyrApdCM4Z8ulBs',
    appId: '1:922484244108:web:6108053e9c300340d605a9',
    messagingSenderId: '922484244108',
    projectId: 'bbm-pln',
    authDomain: 'bbm-pln.firebaseapp.com',
    storageBucket: 'bbm-pln.firebasestorage.app',
    measurementId: 'G-6FTZ0PT7RQ',
  );
}
